spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Book?useUnicode=true&characterEncoding=utf-8
    username: Book
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      use-new-id-generator-mappings: false
      ddl-auto: update
server:
  port: 8080

