spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Book?useUnicode=true&characterEncoding=utf-8
    username: Book
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080

